const ROLE = {
  ADMIN: 1,
  USER: 2,
  GUEST: 3,
};

const ERRORS = {
  UNAUTH: "USER UNAUTHORIZED",
  INVALID_USER: "INVALID USER",
  USER_NOT_FOUND: "USER NOT FOUND",
  TOKEN_NOT_FOUND: "TOKEN NOT FOUND",
  INVALID_TOKEN: "INVALID TOKEN",
};

export { ROLE, ERRORS };
